const VERSION="glab-v12.1.0",CACHE_PREFIX="glab-",STATIC_CACHE=VERSION+"-static",PAGE_CACHE=VERSION+"-pages",PRECACHE=["/","/index.html","/offline.html","/about.html","/privacy.html","/terms.html","/contact.html","/projects/","/articles/","/projects/network-analyzer.html","/projects/noney-bsnl-broadband-nms.html","/projects/rongmei-hymnal.html","/projects/ssh-fleet-doctor.html","/articles/better-light-better-night.html","/articles/learning-from-soil.html","/articles/listening-without-losing-the-music.html","/articles/passkeys-and-the-human-side-of-security.html","/articles/repair-before-replace.html","/articles/responsible-ai.html","/articles/right-sized-ai.html","/articles/security-is-care.html","/articles/small-tools.html","/articles/soil-sensors-need-ground-truth.html","/manifest.webmanifest","/search-index.json","/assets/brand/glab-mark-16.png","/assets/brand/glab-mark-32.png","/assets/brand/glab-mark-48.png","/assets/brand/glab-mark-64.png","/assets/icons/apple-touch-180.png","/assets/icons/glab-192.png","/assets/icons/glab-512.png","/assets/css/00-tokens.css","/assets/css/10-base.css","/assets/css/20-layout.css","/assets/css/30-navigation.css","/assets/css/40-components.css","/assets/css/45-profile.css","/assets/css/50-content.css","/assets/css/60-ads.css","/assets/css/70-responsive.css","/assets/css/80-accessibility.css","/assets/css/90-print.css","/assets/css/main.css","/assets/js/core/dom.js","/assets/js/core/storage.js","/assets/js/core/viewport.js","/assets/js/features/ads.js","/assets/js/features/code-copy.js","/assets/js/features/projects.js","/assets/js/features/pwa.js","/assets/js/features/search.js","/assets/js/features/share.js","/assets/js/main.js","/assets/js/ui/header.js","/assets/js/ui/menu.js","/assets/js/ui/preferences.js","/assets/js/ui/reading.js"];
self.addEventListener("install",event=>{event.waitUntil(caches.open(STATIC_CACHE).then(cache=>cache.addAll(PRECACHE)));});
self.addEventListener("activate",event=>{event.waitUntil(Promise.all([caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith(CACHE_PREFIX)&&!key.startsWith(VERSION)).map(key=>caches.delete(key)))),self.registration.navigationPreload?self.registration.navigationPreload.enable():Promise.resolve()]).then(()=>self.clients.claim()));});
self.addEventListener("message",event=>{if(event.data?.type==="SKIP_WAITING")self.skipWaiting();});
async function networkFirst(event){const request=event.request;try{const response=(await event.preloadResponse)||await fetch(request);if(response&&response.ok){const cache=await caches.open(PAGE_CACHE);cache.put(request,response.clone());}return response;}catch{return(await caches.match(request))||(await caches.match(new URL(request.url).pathname))||(await caches.match("/offline.html"));}}
async function staleWhileRevalidate(request){const cached=await caches.match(request);const fetchPromise=fetch(request).then(async response=>{if(response&&response.ok){const cache=await caches.open(STATIC_CACHE);cache.put(request,response.clone());}return response;}).catch(()=>null);const response=cached||await fetchPromise;return response||Response.error();}
const ROOT_FILES=new Set(["/","/index.html","/offline.html","/about.html","/privacy.html","/terms.html","/contact.html","/manifest.webmanifest","/search-index.json","/feed.xml","/sitemap.xml","/robots.txt"]);
function belongsToGLab(path){return ROOT_FILES.has(path)||path.startsWith("/projects/")||path.startsWith("/articles/")||path.startsWith("/assets/");}
self.addEventListener("fetch",event=>{if(event.request.method!=="GET")return;const url=new URL(event.request.url);if(url.origin!==self.location.origin||!belongsToGLab(url.pathname))return;if(event.request.mode==="navigate"){event.respondWith(networkFirst(event));return;}if(/\.(?:css|js|json|png|webmanifest)$/i.test(url.pathname))event.respondWith(staleWhileRevalidate(event.request));});
